# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/SADDNS/saddns_c

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/SADDNS/saddns_c/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/SADDNS/saddns_c/build/CMakeFiles /root/SADDNS/saddns_c/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/SADDNS/saddns_c/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nsmuter

# Build rule for target.
nsmuter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nsmuter
.PHONY : nsmuter

# fast build rule for target.
nsmuter/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nsmuter.dir/build.make CMakeFiles/nsmuter.dir/build
.PHONY : nsmuter/fast

#=============================================================================
# Target rules for targets named delayns

# Build rule for target.
delayns: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 delayns
.PHONY : delayns

# fast build rule for target.
delayns/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delayns.dir/build.make CMakeFiles/delayns.dir/build
.PHONY : delayns/fast

#=============================================================================
# Target rules for targets named udpscan

# Build rule for target.
udpscan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 udpscan
.PHONY : udpscan

# fast build rule for target.
udpscan/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/udpscan.dir/build.make CMakeFiles/udpscan.dir/build
.PHONY : udpscan/fast

#=============================================================================
# Target rules for targets named attack_recur

# Build rule for target.
attack_recur: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 attack_recur
.PHONY : attack_recur

# fast build rule for target.
attack_recur/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_recur.dir/build.make CMakeFiles/attack_recur.dir/build
.PHONY : attack_recur/fast

#=============================================================================
# Target rules for targets named attack_recur_ns

# Build rule for target.
attack_recur_ns: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 attack_recur_ns
.PHONY : attack_recur_ns

# fast build rule for target.
attack_recur_ns/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_recur_ns.dir/build.make CMakeFiles/attack_recur_ns.dir/build
.PHONY : attack_recur_ns/fast

#=============================================================================
# Target rules for targets named attack_forwr

# Build rule for target.
attack_forwr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 attack_forwr
.PHONY : attack_forwr

# fast build rule for target.
attack_forwr/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_forwr.dir/build.make CMakeFiles/attack_forwr.dir/build
.PHONY : attack_forwr/fast

attack_forwr.o: attack_forwr.c.o
.PHONY : attack_forwr.o

# target to build an object file
attack_forwr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_forwr.dir/build.make CMakeFiles/attack_forwr.dir/attack_forwr.c.o
.PHONY : attack_forwr.c.o

attack_forwr.i: attack_forwr.c.i
.PHONY : attack_forwr.i

# target to preprocess a source file
attack_forwr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_forwr.dir/build.make CMakeFiles/attack_forwr.dir/attack_forwr.c.i
.PHONY : attack_forwr.c.i

attack_forwr.s: attack_forwr.c.s
.PHONY : attack_forwr.s

# target to generate assembly for a file
attack_forwr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_forwr.dir/build.make CMakeFiles/attack_forwr.dir/attack_forwr.c.s
.PHONY : attack_forwr.c.s

attack_recur.o: attack_recur.c.o
.PHONY : attack_recur.o

# target to build an object file
attack_recur.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_recur.dir/build.make CMakeFiles/attack_recur.dir/attack_recur.c.o
.PHONY : attack_recur.c.o

attack_recur.i: attack_recur.c.i
.PHONY : attack_recur.i

# target to preprocess a source file
attack_recur.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_recur.dir/build.make CMakeFiles/attack_recur.dir/attack_recur.c.i
.PHONY : attack_recur.c.i

attack_recur.s: attack_recur.c.s
.PHONY : attack_recur.s

# target to generate assembly for a file
attack_recur.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_recur.dir/build.make CMakeFiles/attack_recur.dir/attack_recur.c.s
.PHONY : attack_recur.c.s

attack_recur_ns.o: attack_recur_ns.c.o
.PHONY : attack_recur_ns.o

# target to build an object file
attack_recur_ns.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_recur_ns.dir/build.make CMakeFiles/attack_recur_ns.dir/attack_recur_ns.c.o
.PHONY : attack_recur_ns.c.o

attack_recur_ns.i: attack_recur_ns.c.i
.PHONY : attack_recur_ns.i

# target to preprocess a source file
attack_recur_ns.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_recur_ns.dir/build.make CMakeFiles/attack_recur_ns.dir/attack_recur_ns.c.i
.PHONY : attack_recur_ns.c.i

attack_recur_ns.s: attack_recur_ns.c.s
.PHONY : attack_recur_ns.s

# target to generate assembly for a file
attack_recur_ns.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_recur_ns.dir/build.make CMakeFiles/attack_recur_ns.dir/attack_recur_ns.c.s
.PHONY : attack_recur_ns.c.s

delayns.o: delayns.c.o
.PHONY : delayns.o

# target to build an object file
delayns.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delayns.dir/build.make CMakeFiles/delayns.dir/delayns.c.o
.PHONY : delayns.c.o

delayns.i: delayns.c.i
.PHONY : delayns.i

# target to preprocess a source file
delayns.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delayns.dir/build.make CMakeFiles/delayns.dir/delayns.c.i
.PHONY : delayns.c.i

delayns.s: delayns.c.s
.PHONY : delayns.s

# target to generate assembly for a file
delayns.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delayns.dir/build.make CMakeFiles/delayns.dir/delayns.c.s
.PHONY : delayns.c.s

dns.o: dns.c.o
.PHONY : dns.o

# target to build an object file
dns.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nsmuter.dir/build.make CMakeFiles/nsmuter.dir/dns.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delayns.dir/build.make CMakeFiles/delayns.dir/dns.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/udpscan.dir/build.make CMakeFiles/udpscan.dir/dns.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_recur.dir/build.make CMakeFiles/attack_recur.dir/dns.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_recur_ns.dir/build.make CMakeFiles/attack_recur_ns.dir/dns.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_forwr.dir/build.make CMakeFiles/attack_forwr.dir/dns.c.o
.PHONY : dns.c.o

dns.i: dns.c.i
.PHONY : dns.i

# target to preprocess a source file
dns.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nsmuter.dir/build.make CMakeFiles/nsmuter.dir/dns.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delayns.dir/build.make CMakeFiles/delayns.dir/dns.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/udpscan.dir/build.make CMakeFiles/udpscan.dir/dns.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_recur.dir/build.make CMakeFiles/attack_recur.dir/dns.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_recur_ns.dir/build.make CMakeFiles/attack_recur_ns.dir/dns.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_forwr.dir/build.make CMakeFiles/attack_forwr.dir/dns.c.i
.PHONY : dns.c.i

dns.s: dns.c.s
.PHONY : dns.s

# target to generate assembly for a file
dns.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nsmuter.dir/build.make CMakeFiles/nsmuter.dir/dns.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delayns.dir/build.make CMakeFiles/delayns.dir/dns.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/udpscan.dir/build.make CMakeFiles/udpscan.dir/dns.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_recur.dir/build.make CMakeFiles/attack_recur.dir/dns.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_recur_ns.dir/build.make CMakeFiles/attack_recur_ns.dir/dns.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_forwr.dir/build.make CMakeFiles/attack_forwr.dir/dns.c.s
.PHONY : dns.c.s

network.o: network.c.o
.PHONY : network.o

# target to build an object file
network.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nsmuter.dir/build.make CMakeFiles/nsmuter.dir/network.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delayns.dir/build.make CMakeFiles/delayns.dir/network.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/udpscan.dir/build.make CMakeFiles/udpscan.dir/network.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_recur.dir/build.make CMakeFiles/attack_recur.dir/network.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_recur_ns.dir/build.make CMakeFiles/attack_recur_ns.dir/network.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_forwr.dir/build.make CMakeFiles/attack_forwr.dir/network.c.o
.PHONY : network.c.o

network.i: network.c.i
.PHONY : network.i

# target to preprocess a source file
network.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nsmuter.dir/build.make CMakeFiles/nsmuter.dir/network.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delayns.dir/build.make CMakeFiles/delayns.dir/network.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/udpscan.dir/build.make CMakeFiles/udpscan.dir/network.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_recur.dir/build.make CMakeFiles/attack_recur.dir/network.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_recur_ns.dir/build.make CMakeFiles/attack_recur_ns.dir/network.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_forwr.dir/build.make CMakeFiles/attack_forwr.dir/network.c.i
.PHONY : network.c.i

network.s: network.c.s
.PHONY : network.s

# target to generate assembly for a file
network.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nsmuter.dir/build.make CMakeFiles/nsmuter.dir/network.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delayns.dir/build.make CMakeFiles/delayns.dir/network.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/udpscan.dir/build.make CMakeFiles/udpscan.dir/network.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_recur.dir/build.make CMakeFiles/attack_recur.dir/network.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_recur_ns.dir/build.make CMakeFiles/attack_recur_ns.dir/network.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_forwr.dir/build.make CMakeFiles/attack_forwr.dir/network.c.s
.PHONY : network.c.s

nsmuter.o: nsmuter.c.o
.PHONY : nsmuter.o

# target to build an object file
nsmuter.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nsmuter.dir/build.make CMakeFiles/nsmuter.dir/nsmuter.c.o
.PHONY : nsmuter.c.o

nsmuter.i: nsmuter.c.i
.PHONY : nsmuter.i

# target to preprocess a source file
nsmuter.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nsmuter.dir/build.make CMakeFiles/nsmuter.dir/nsmuter.c.i
.PHONY : nsmuter.c.i

nsmuter.s: nsmuter.c.s
.PHONY : nsmuter.s

# target to generate assembly for a file
nsmuter.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nsmuter.dir/build.make CMakeFiles/nsmuter.dir/nsmuter.c.s
.PHONY : nsmuter.c.s

scanner.o: scanner.c.o
.PHONY : scanner.o

# target to build an object file
scanner.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/udpscan.dir/build.make CMakeFiles/udpscan.dir/scanner.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_recur.dir/build.make CMakeFiles/attack_recur.dir/scanner.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_recur_ns.dir/build.make CMakeFiles/attack_recur_ns.dir/scanner.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_forwr.dir/build.make CMakeFiles/attack_forwr.dir/scanner.c.o
.PHONY : scanner.c.o

scanner.i: scanner.c.i
.PHONY : scanner.i

# target to preprocess a source file
scanner.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/udpscan.dir/build.make CMakeFiles/udpscan.dir/scanner.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_recur.dir/build.make CMakeFiles/attack_recur.dir/scanner.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_recur_ns.dir/build.make CMakeFiles/attack_recur_ns.dir/scanner.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_forwr.dir/build.make CMakeFiles/attack_forwr.dir/scanner.c.i
.PHONY : scanner.c.i

scanner.s: scanner.c.s
.PHONY : scanner.s

# target to generate assembly for a file
scanner.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/udpscan.dir/build.make CMakeFiles/udpscan.dir/scanner.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_recur.dir/build.make CMakeFiles/attack_recur.dir/scanner.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_recur_ns.dir/build.make CMakeFiles/attack_recur_ns.dir/scanner.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_forwr.dir/build.make CMakeFiles/attack_forwr.dir/scanner.c.s
.PHONY : scanner.c.s

udpscan.o: udpscan.c.o
.PHONY : udpscan.o

# target to build an object file
udpscan.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/udpscan.dir/build.make CMakeFiles/udpscan.dir/udpscan.c.o
.PHONY : udpscan.c.o

udpscan.i: udpscan.c.i
.PHONY : udpscan.i

# target to preprocess a source file
udpscan.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/udpscan.dir/build.make CMakeFiles/udpscan.dir/udpscan.c.i
.PHONY : udpscan.c.i

udpscan.s: udpscan.c.s
.PHONY : udpscan.s

# target to generate assembly for a file
udpscan.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/udpscan.dir/build.make CMakeFiles/udpscan.dir/udpscan.c.s
.PHONY : udpscan.c.s

util.o: util.c.o
.PHONY : util.o

# target to build an object file
util.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nsmuter.dir/build.make CMakeFiles/nsmuter.dir/util.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delayns.dir/build.make CMakeFiles/delayns.dir/util.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/udpscan.dir/build.make CMakeFiles/udpscan.dir/util.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_recur.dir/build.make CMakeFiles/attack_recur.dir/util.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_recur_ns.dir/build.make CMakeFiles/attack_recur_ns.dir/util.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_forwr.dir/build.make CMakeFiles/attack_forwr.dir/util.c.o
.PHONY : util.c.o

util.i: util.c.i
.PHONY : util.i

# target to preprocess a source file
util.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nsmuter.dir/build.make CMakeFiles/nsmuter.dir/util.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delayns.dir/build.make CMakeFiles/delayns.dir/util.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/udpscan.dir/build.make CMakeFiles/udpscan.dir/util.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_recur.dir/build.make CMakeFiles/attack_recur.dir/util.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_recur_ns.dir/build.make CMakeFiles/attack_recur_ns.dir/util.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_forwr.dir/build.make CMakeFiles/attack_forwr.dir/util.c.i
.PHONY : util.c.i

util.s: util.c.s
.PHONY : util.s

# target to generate assembly for a file
util.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nsmuter.dir/build.make CMakeFiles/nsmuter.dir/util.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delayns.dir/build.make CMakeFiles/delayns.dir/util.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/udpscan.dir/build.make CMakeFiles/udpscan.dir/util.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_recur.dir/build.make CMakeFiles/attack_recur.dir/util.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_recur_ns.dir/build.make CMakeFiles/attack_recur_ns.dir/util.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_forwr.dir/build.make CMakeFiles/attack_forwr.dir/util.c.s
.PHONY : util.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... attack_forwr"
	@echo "... attack_recur"
	@echo "... attack_recur_ns"
	@echo "... delayns"
	@echo "... nsmuter"
	@echo "... udpscan"
	@echo "... attack_forwr.o"
	@echo "... attack_forwr.i"
	@echo "... attack_forwr.s"
	@echo "... attack_recur.o"
	@echo "... attack_recur.i"
	@echo "... attack_recur.s"
	@echo "... attack_recur_ns.o"
	@echo "... attack_recur_ns.i"
	@echo "... attack_recur_ns.s"
	@echo "... delayns.o"
	@echo "... delayns.i"
	@echo "... delayns.s"
	@echo "... dns.o"
	@echo "... dns.i"
	@echo "... dns.s"
	@echo "... network.o"
	@echo "... network.i"
	@echo "... network.s"
	@echo "... nsmuter.o"
	@echo "... nsmuter.i"
	@echo "... nsmuter.s"
	@echo "... scanner.o"
	@echo "... scanner.i"
	@echo "... scanner.s"
	@echo "... udpscan.o"
	@echo "... udpscan.i"
	@echo "... udpscan.s"
	@echo "... util.o"
	@echo "... util.i"
	@echo "... util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

